import React from 'react';

const Disclaimer = () => {
  return (
    <div style={{ padding: "2px", margin: "2px" }}>
      <style>
        {`
          @media print {
            body {
              font-size: 12px;
              line-height: 1.5;
              margin: 10px;
            }
            div.print-container {
              max-height: 400px;
              overflow-y: scroll;
              padding: 2px;
              margin: 2px;
              break-inside: avoid;
            }
          }
        `}
      </style>
      <div className="print-container">
        <br />
        <p><strong>TERMS AND CONDITIONS FOR USE OF TRUCKMILES® SERVICES</strong></p>
        <p>THIS AGREEMENT ("AGREEMENT") GOVERNS THE USE OF THE TRUCKMILES ONLINE WEBSITE (THE "WEBSITE") AND ALL SERVICES AVAILABLE AT OR THROUGH THE WEBSITE (THE "SERVICES") INCLUDING ANY MOBILE APPLICATIONS. BY USING THE SERVICES, YOU AGREE TO THE TERMS OF THIS AGREEMENT. IF YOU DO NOT AGREE WITH THESE TERMS AND CONDITIONS, YOU MUST NOT ACCEPT THIS AGREEMENT AND MAY NOT USE THE SERVICES. TRUCKMILES IS A PRODUCT OF PROMILES® SOFTWARE DEVELOPMENT CORPORATION. This is a summary version of the AGREEMENT. You can review the most current version of the COMPLETE Agreement at any time by visiting ProMiles.com/TruckMilesTerms.asp This summary on no way limits the complete AGREEMENT.</p>
        <p>PSDC SOFTWARE For purposes of this agreement, SOFTWARE is defined as any product or data made available to YOU by ProMiles Software Development Corporation in connection with the SERVICES. Usage of SOFTWARE without accepting this agreement is strictly prohibited.</p>
        <p>USE OF ONLINE SERVICES YOU acknowledge and agree that:</p>
        <ul>
          <li>YOU will not use the SERVICES in any manner or for any purpose that is prohibited by the terms and conditions;</li>
          <li>YOU will not use the SERVICES for any illegal or unauthorized purpose and that YOU will not, in the use of the SERVICES, violate any laws in YOUR jurisdiction;</li>
          <li>YOU will not take or attempt any action that, in the sole discretion of PSDC, imposes or may impose an unreasonable or disproportionately large load or burden on the Website or such operation's infrastructure;</li>
          <li>YOU have not falsely identified yourself, nor provided any false information, to gain access to the SERVICES;</li>
        </ul>
        <p>USER RESPONSIBILITY: DRIVING DIRECTIONS PSDC strives to collect and present the most accurate driving directions possible for its SOFTWARE. These directions are not guaranteed to be accurate. YOU accept the responsibility for YOURSELF and for any others with whom you share directions generated by the SOFTWARE to obey all posted traffic signs and to obey all national, state, and local laws, rules, restrictions, regulations, and law enforcement personnel governing travel wherever YOU or those with whom YOU share directions may drive. PSDC accepts no responsibility or liability for any mishaps or damages, financial or otherwise, that result from using its driving directions, as outlined in the INDEMNITY section below.</p>
        <p>USER RESPONSIBILITY: DISTRACTED DRIVING Review maps before departing. If YOU need to refer to a map or driving directions, pull over to a safe location. Distracted driving could divert a person's attention away from the primary task of driving. All distractions can endanger driver, passenger, general motorist and bystander safety. PSDC accepts no responsibility or liability incurred by attempting to use the SOFTWARE or any derivative thereof while driving.</p>
        <p>LIMITATION OF LIABILITY IF YOU ARE DISSATISFIED WITH ANY PORTION OF THE SERVICES OR SOFTWARE, OR WITH ANY OF THESE TERMS AND CONDITIONS, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USING THE SERVICES AND SOFTWARE.</p>
        <p>INDEMNITY YOU understand that your use of PSDC SOFTWARE is at your own risk. YOU agree to hold PSDC, its affiliates, resellers, partners, officers, agents, and employees blameless for any set-back, damage, inconvenience, or other difficulty, financial or otherwise, that may arise from the use of its SOFTWARE.</p>
        <p>TRADEMARKS The following trademarks are owned by PSDC: "ProMiles" - is a registered trademark of ProMiles Software Development Corporation. "TruckMiles" - is a registered trademark of ProMiles Software Development Corporation. This Agreement does not provide any license or rights to YOU to use such trademarks.</p>
        <p>THIRD PARTY RIGHTS AND TRADEMARKS The SOFTWARE may include a portion, subset or derivative compilations from third parties. By using the SERVICES and SOFTWARE, YOU agree to the Terms and Conditions of these providers in their entirety. Third parties retain the right to modify their Terms and Conditions independently of PSDC. Copyright © 1994 - 2019 ProMiles Software Development Corporation. Any rights not expressly granted herein are reserved. TruckMiles™ inquiries should be directed to info@truckmiles.com, or sales@truckmiles.com as appropriate.</p>
      </div>
    </div>
  );
};

export default Disclaimer;
